# add to end of /boot/loader.conf

# Added for M270 Platform Support
# hint.ix.0.enable_mdio=1         # This is specific to v16.0
# hint.ix.1.enable_mdio=1         # This is not needed.  Do not uncomment this line.

hint.mdio.0.at="ix0"
hint.e6000sw.0.at="mdio1"
hint.e6000sw.0.addr="0x0"
hint.e6000sw.0.port0disabled="1"
hint.e6000sw.0.is6190x="1"
hint.e6000sw.0.port9cpu="1"
hint.e6000sw.0.port10cpu="1"
hint.e6000sw.0.port9speed="2500"
hint.e6000sw.0.port10speed="2500"

