#!/bin/sh
#
# Script to setup the switch in the M270
#

# /usr/local/etc/rc.d/configure_switch.sh
# chmod +x /usr/local/etc/rc.d/configure_switch.sh

# For v16.0 you will need to mkdir /usr/local/etc/rc.d

# IMPORTANT - The port configuration MUST MATCH what is in rc.conf!

# PROVIDE: config_switch
# REQUIRE: kld FILESYSTEMS
# BEFORE:  netif NETWORKING

name="m270_switch"
rcvar="m270_switch_enable"
start_cmd="m270_switch_start"

m270_switch_start() {
    echo "Configuring M270 Switch ... "
    logger Configuring M270 Switch ...
    
    # Set global mode
    etherswitchcfg config vlan_mode DOT1Q
    
    # Map internal switch physical ports 1-8 to individual VLAN groups tagged to CPU facing port 9 or 10
    # This MUST match rc.conf configuration

    # This is the 4x4 configuration where 4 ports are bound to ix0 and 4 ports are bound to ix1
    # ix0
    etherswitchcfg vlangroup1 vlan 901 members 1,9t
    etherswitchcfg vlangroup2 vlan 902 members 2,9t
    etherswitchcfg vlangroup3 vlan 903 members 3,9t
    etherswitchcfg vlangroup4 vlan 904 members 4,9t
    # ix1
    etherswitchcfg vlangroup5 vlan 905 members 5,10t
    etherswitchcfg vlangroup6 vlan 906 members 6,10t
    etherswitchcfg vlangroup7 vlan 907 members 7,10t
    etherswitchcfg vlangroup8 vlan 908 members 8,10t

    # This is the standard firewall 1x7 config where 1 port is bound to ix0 and the remaining are bound to ix1
    # ix0
    # etherswitchcfg vlangroup1 vlan 901 members 1,9t
    # ix1
    # etherswitchcfg vlangroup2 vlan 902 members 2,10t
    # etherswitchcfg vlangroup3 vlan 903 members 3,10t
    # etherswitchcfg vlangroup4 vlan 904 members 4,10t
    # etherswitchcfg vlangroup5 vlan 905 members 5,10t
    # etherswitchcfg vlangroup6 vlan 906 members 6,10t
    # etherswitchcfg vlangroup7 vlan 907 members 7,10t
    # etherswitchcfg vlangroup8 vlan 908 members 8,10t

    etherswitchcfg port1 pvid 901
    etherswitchcfg port2 pvid 902
    etherswitchcfg port3 pvid 903
    etherswitchcfg port4 pvid 904
    etherswitchcfg port5 pvid 905
    etherswitchcfg port6 pvid 906
    etherswitchcfg port7 pvid 907
    etherswitchcfg port8 pvid 908
    
    echo "M270 Switch Configuration Complete"
    logger M270 Switch Configuration Complete
}
load_rc_config $name
run_rc_command "$1"
