# Add to end of /etc/rc.conf

# Late-load the e6000sw driver so it doesn't kernel panic during the loader stage
kld_list="e6000sw"         # This is specific to v16.0
# https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=295985

# Enable our custom switch matrix initialization script
m270_switch_enable="YES"

# Tell the kernel to spawn virtual VLAN adapters tied to your CPU port (ix0/ix1)
# Please make sure that what ever config you use it matches in the switch config

# This is the 4x4 configuration where 4 ports are bound to ix0 and 4 ports are bound to ix1
vlans_ix0="901 902 903 904"
vlans_ix1="905 906 907 908"

# This is the standard firewall 1x7 config where 1 port is bound to ix0 and the remaining are bound to ix1
#vlans_ix0="901"
#vlans_ix1="902 903 904 905 906 907 908"

# Explicitly ensure the parent physical ports stay UP without an IP
ifconfig_ix0="up promisc"
ifconfig_ix1="up promisc"

# You must determine the original ix0 and ix1 MAC address and record them below:
# ix0 = 00:a0:c9:00:00:02
# ix1 = 34:12:78:56:01:03

# Then when creating the virtual interfaces, you must increment the MACs from the parent!
# Technically, you can add any here, but it makes sense to associate with the parent.
# For some reason, when ether random is used, the switch stops communicating on the newtwork.

# Configure each physical port via its matching VLAN to fetch an IP from DHCP
# This MUST match the configuration you have above!

# This is the 4x4 configuration where 4 ports are bound to ix0 and 4 ports are bound to ix1
# ix0 subports
ifconfig_ix0_901="DHCP link 00:a0:c9:00:00:03"    # Front Port 0
ifconfig_ix0_902="DHCP link 00:a0:c9:00:00:04"    # Front Port 1
ifconfig_ix0_903="DHCP link 00:a0:c9:00:00:05"    # Front Port 2
ifconfig_ix0_904="DHCP link 00:a0:c9:00:00:06"    # Front Port 3
# ix1 subports
ifconfig_ix1_905="DHCP link 34:12:78:56:01:04"    # Front Port 4
ifconfig_ix1_906="DHCP link 34:12:78:56:01:05"    # Front Port 5
ifconfig_ix1_907="DHCP link 34:12:78:56:01:06"    # Front Port 6
ifconfig_ix1_908="DHCP link 34:12:78:56:01:07"    # Front Port 7

# Here you can add static entries for initial entry
#ifconfig_ix1_905="inet 192.168.168.168 netmask 255.255.255.0 mtu 9000"

# Speed up boots by running dhclient in the background
background_dhclient="YES"
