# Add to end of /etc/rc.conf

# Late-load the e6000sw driver so it doesn't kernel panic during the loader stage
kld_list="e6000sw"         # This is specific to v16.0
# https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=295985

# Enable our custom switch matrix initialization script
m270_switch_enable="YES"

# Tell the kernel to spawn virtual VLAN adapters tied to your CPU port (ix0/ix1)
# Please make sure that what ever config you use it matches in the switch config

# This is the 4x4 configuration where 4 ports are bound to ix0 and 4 ports are bound to ix1
vlans_ix0="901 902 903 904"
vlans_ix1="905 906 907 908"

# This is the standard firewall 1x7 config where 1 port is bound to ix0 and the remaining are bound to ix1
#vlans_ix0="901"
#vlans_ix1="902 903 904 905 906 907 908"

# Explicitly ensure the parent physical ports stay UP without an IP and put them in promiscuous mode
# Also since all of the downstream child devices inherit the MTU of the parent, we must set them here
ifconfig_ix0="mtu 9000 up promisc"
ifconfig_ix1="mtu 9000 up promisc"

# Because of an issue with the child ports inheriting the parent MAC, we have to explicitly set
# the MAC address here.
# NOTE 1: 'ether' does not work on virtual switch ports - use 'link' instead
# NOTE 2: Because of the way etherswitch works, you can only perform ONE command here.  To do anything else,
#         we will create start interface scripts: /etc/start_if.ix0.901

# This is the 4x4 configuration where 4 ports are bound to ix0 and 4 ports are bound to ix1
# ix0 virtual ports
ifconfig_ix0_901="link 52:54:00:78:32:00"    # Front Port 0
ifconfig_ix0_902="link 52:54:00:78:32:01"    # Front Port 1
ifconfig_ix0_903="link 52:54:00:78:32:02"    # Front Port 2
ifconfig_ix0_904="link 52:54:00:78:32:03"    # Front Port 3
# ix1 virtual ports
ifconfig_ix1_905="link 52:54:00:78:32:04"    # Front Port 4
ifconfig_ix1_906="link 52:54:00:78:32:05"    # Front Port 5
ifconfig_ix1_907="link 52:54:00:78:32:06"    # Front Port 6
ifconfig_ix1_908="link 52:54:00:78:32:07"    # Front Port 7

# Speed up boots by running dhclient in the background
background_dhclient="YES"

# Don't froget to set your correct default router/gateway here:
defaultrouter="192.168.1.1"
