# Add to end of /etc/rc.conf

# kld_list="e6000sw"         # This is specific to v16.0
# https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=295985

ifconfig_ix0="up"
ifconfig_ix1="up"

# IMPORTANT - The port configuration MUST MATCH the config_switch.sh script!

# This is the 4x4 configuration where 4 ports are bound to ix0 and 4 ports are bound to ix1
vlans_ix0="port0 port1 port2 port3"
vlans_ix1="port4 port5 port6 port7"

# This is the standard firewall 1x7 config where 1 port is bound to ix0 and the remaining are bound to ix1
# vlans_ix0="port0"
# vlans_ix1="port1 port2 port3 port4 port5 port6 port7"

create_args_port0="vlan 110"
create_args_port1="vlan 120"
create_args_port2="vlan 130"
create_args_port3="vlan 140"
create_args_port4="vlan 150"
create_args_port5="vlan 160"
create_args_port6="vlan 170"
create_args_port7="vlan 180"

# All of the interfaces have the same MAC.  So we must assign a new MAC.
ifconfig port0 ether random
ifconfig port1 ether random
ifconfig port2 ether random
ifconfig port3 ether random
ifconfig port4 ether random
ifconfig port5 ether random
ifconfig port6 ether random
ifconfig port7 ether random

# Set the front panel port thay you will use to DHCP for ease of initial access
#ifconfig_port0="dhcp"
#ifconfig_port1="dhcp"
#ifconfig_port2="dhcp"
#ifconfig_port3="dhcp"
ifconfig_port4="dhcp"
#ifconfig_port5="dhcp"
#ifconfig_port6="dhcp"
#ifconfig_port7="dhcp"

#ifconfig_port0="inet 192.168.168.168 netmask 255.255.255.0 mtu 9000"

config_switch_enable="YES"
