# Add to end of /etc/rc.conf

# Late-load the e6000sw driver so it doesn't kernel panic during the loader stage
kld_list="e6000sw"         # This is specific to v16.0
# https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=295985

# Explicitly ensure the parent physical ports stay UP without an IP and put them in promiscuous mode
ifconfig_ix0="up promisc"
ifconfig_ix1="up promisc"

# IMPORTANT - The port configuration MUST MATCH the across all scripts!
create_args_port1="vlan 901"
create_args_port2="vlan 902"
create_args_port3="vlan 903"
create_args_port4="vlan 904"
create_args_port5="vlan 905"
create_args_port6="vlan 906"
create_args_port7="vlan 907"
create_args_port8="vlan 908"

# This is the 4x4 configuration where 4 ports are bound to ix0 and 4 ports are bound to ix1
vlans_ix0="port1 port2 port3 port4"
vlans_ix1="port5 port6 port7 port8"

# This is the standard firewall 1x7 config where 1 port is bound to ix0 and the remaining are bound to ix1
# vlans_ix0="port1"
# vlans_ix1="port2 port3 port4 port5 port6 port7 port8"

# Set the front panel port thay you will use to DHCP for ease of initial access
ifconfig_port1="dhcp ether random"
ifconfig_port2="dhcp ether random"
ifconfig_port3="dhcp ether random"
ifconfig_port4="dhcp ether random"
ifconfig_port5="dhcp ether random"
ifconfig_port6="dhcp ether random"
ifconfig_port7="dhcp ether random"
ifconfig_port8="dhcp ether random"

#ifconfig_port1="inet 192.168.168.168 netmask 255.255.255.0 mtu 9000"
m270_switch_enable="YES"

# Speed up boots by running dhclient in the background
background_dhclient="YES"